import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateContractReport = (result: any, fileName: string) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(0, 51, 102); // Dark blue legal header
    doc.text("Contract Analysis Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on ${date}`, 14, 28);
    doc.text(`Document: ${fileName}`, 14, 33);
    doc.line(14, 36, 196, 36);

    // Summary Section
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text("Executive Summary", 14, 46);

    doc.setFontSize(10);
    doc.setTextColor(0);
    const summaryLines = doc.splitTextToSize(result.summary, 182);
    doc.text(summaryLines, 14, 52);

    let currentY = 52 + (summaryLines.length * 5) + 10;

    // Key Details Section
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text("Key Contract Details", 14, currentY);
    currentY += 6;

    doc.setFontSize(10);
    doc.setTextColor(0);
    result.key_details.forEach((detail: string) => {
        const detailLines = doc.splitTextToSize(`• ${detail}`, 182);
        doc.text(detailLines, 14, currentY);
        currentY += (detailLines.length * 5);
    });

    currentY += 10;

    // Risks Table
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text("Risk Assessment breakdown", 14, currentY);
    currentY += 4;

    const tableData = result.risks.map((risk: any) => [
        risk.severity,
        risk.clause,
        risk.explanation
    ]);

    autoTable(doc, {
        startY: currentY,
        head: [["Severity", "Clause/Section", "Legal Explanation"]],
        body: tableData,
        headStyles: { fillColor: [0, 51, 102] },
        columnStyles: {
            0: { cellWidth: 20 },
            1: { cellWidth: 60 },
            2: { cellWidth: 102 }
        }
    });

    // Final Score
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(16);
    doc.setTextColor(0, 51, 102);
    doc.text(`Overall Safety Score: ${result.score}/100`, 14, finalY);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Disclaimer: This report is generated by AI for informational purposes only and does not constitute legal advice.", 14, 285);

    // Download
    doc.save(`Analysis_Report_${fileName.replace(/\.[^/.]+$/, "")}.pdf`);
};
